"""empty message

Revision ID: 21b5c9799c6
Revises: 52e1d4a5c3d1
Create Date: 2015-11-05 01:06:30.298237

"""

# revision identifiers, used by Alembic.
revision = '21b5c9799c6'
down_revision = '52e1d4a5c3d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('done', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'done')
    ### end Alembic commands ###
