"""empty message

Revision ID: 25e3b9585caf
Revises: 4c1ecd63ff6a
Create Date: 2015-11-04 15:51:02.153173

"""

# revision identifiers, used by Alembic.
revision = '25e3b9585caf'
down_revision = '4c1ecd63ff6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('user', 'hashed_password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_id'], [u'list.id'], name=u'item_list_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'item_pkey')
    )
    op.drop_table('task')
    ### end Alembic commands ###
