"""empty message

Revision ID: 52e1d4a5c3d1
Revises: 25e3b9585caf
Create Date: 2015-11-04 21:45:54.722422

"""

# revision identifiers, used by Alembic.
revision = '52e1d4a5c3d1'
down_revision = '25e3b9585caf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    ### end Alembic commands ###
